### ISSUE TITLE
Unit-test for RAP Event handler class

### ISSUE THREAD

**Issue by DenisTis** [SAP-samples/abap-cheat-sheets#10]
Dear colleagues, 
I am working in Concur integration team in same company. 
I had to implement custom event receiver, but as you know, it is not possible to release my task because unit test coverage is too low.
Could you please enhance the cheat-sheet for it as well?

**Comment by DenisTis** [comment]
More details: 
when in unit-test class this instance is generated:
f_cut = NEW lcl_abap_behv_event_handler(  ).
then there is an error: 
Instances of the abstract class "LCL_ABAP_BEHV_EVENT_HANDLER" cannot be generated.

**Comment by danrega** [comment]
Refer to the documentation for more information:
- [https://help.sap.com/docs/abap-cloud/abap-rap/agency-scenario-refining-test-class-structure](https://help.sap.com/docs/abap-cloud/abap-rap/agency-scenario-refining-test-class-structure)
- [`CREATE OBJECT, FOR TESTING`](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapcreate_object_for_testing.htm)
