### ISSUE TITLE
error when pull example

### ISSUE THREAD

**Issue by popsteve** [SAP-samples/abap-cheat-sheets#14]
Hi team, when activate the objects in ABAPgit encounter an error below.
Function CAST: Type STRING of Parameter 1 not supported
![image](https://github.com/user-attachments/assets/a3dc57e7-66e0-4ae6-a5e5-87058ec92c36)

![image](https://github.com/user-attachments/assets/49a4955f-566c-4a28-8ee8-5aef7ed290bc)

**Comment by danrega** [comment]
Hallo @popsteve,
thanks for reaching out. In which system environment did you import the repo (SAP BTP, classic ABAP)? Which ABAP version do you have? Note the descriptions in the README. The main branch is for the SAP BTP ABAP environment only. The other branches v755 - v758 support the respective ABAP releases in classic ABAP (7.55 - 7.58).
