### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by mbtools** [SAP-samples/abap-cheat-sheets#6]
Several code snippets have issues with ABAP syntax highlighting. This is caused by using `tab` or `shift-space` as whitespace instead of just `space`. You can see an example in https://github.com/pvl/abap.tmbundle/issues/85.

If you want this fixed, you will have to replace the whitespace in ABAP code with `spaces`.

**Comment by Nazarakram** [comment]
Hallo there
Good Day

I don't understand why I'm recovering this email?
. Thanks and regards

Yaser Alnazar

00 4366565664925

**Comment by mbtools** [comment]
i guess you subscribed to updates for this repo, @Nazarakram

**Comment by Nazarakram** [comment]
Thanks, I'll check it out.

**Comment by danrega** [comment]
Thanks for the hint. Most of the ABAP syntax highlighting should be corrected. Some additions still remain unhighlighted.

**Comment by mbtools** [comment]
Looks good! the rest should work, once GitHub pulls the latest version of the grammar. 

You can test the code snippet as described [here](https://github.com/pvl/abap.tmbundle#testing) already. 

If something is missing, just open an [issue](https://github.com/pvl/abap.tmbundle/issues/new) and we will add it.

**Comment by Nazarakram** [comment]
Awesome, thanks!
