### ISSUE TITLE
Object Oriented SAP LUW in on Premise

### ISSUE THREAD

**Issue by OlegBash599** [SAP-samples/abap-cheat-sheets#9]
Hello,
For some years I am using object-oriented approach for database saving. I found it useful. The details is [here](https://blogs.sap.com/2022/08/21/database-update-with-utility-anytab-updatetask/). 
The main idea: to avoid create new function modules each time and to be able to log and control data via ABAP Objects approach. Also there is a check point and log-point group inside which could be helpful for Debug purposes (like in ALV-classes).
 

Is it possible to include information about it into [SAP LUW cheat sheet](https://github.com/SAP-samples/abap-cheat-sheets/blob/main/17_SAP_LUW.md)? into [More information](https://github.com/SAP-samples/abap-cheat-sheets/blob/main/17_SAP_LUW.md#more-information) part? 😊

it is just try to share good practise from my point of view.

**Comment by danrega** [comment]
Hi Oleg, 
thanks for reaching out. If you have suggestions (such as issues found, missing/additional syntax to be covered), please feel free to address them. For other materials, custom code and links, please use your own blogs and GitHub repositories (which are already available in this case). 
Thanks and kind regards
